### ISSUE TITLE
Problem with product images (frontend)

### ISSUE THREAD

**Issue by Heart1010** [citruscart/citruscart#1]
When I uploaded two or more images in/for a product I can see these other picture in the product details view in frontend above the first/big picture. But when I click such a new picture nothing happens. Error console shows:

```
Uncaught TypeError: Cannot read property 'src' of undefined index.php?option=com_citruscart&controller=products&view=products&task=view&id=4&Itemid=385:352
changeAltImage index.php?option=com_citruscart&controller=products&view=products&task=view&id=4&Itemid=385:352
onclick index.php?option=com_citruscart&controller=products&view=products&task=view&id=4&Itemid=385:328
```

![bildschirmfoto vom 2014-07-16 22 45 32](https://cloud.githubusercontent.com/assets/1481680/3605404/fe7aba54-0d2a-11e4-9ac6-81d6f8ae7946.png)

(I downloaded a fresh copy from your site and install it but still the same problem...)

**Comment by priyabose** [comment]
We have run repeated test and we didn't find the issue. Can you provide a link to check ?

**Comment by Heart1010** [comment]
sure... I also checked your demo1 and here the same error(s) appear(s) when I want to see the left small image (click on that small product image)

http://demo1.citruscart.org/index.php/component/citruscart/products/view/1/16-rajputs-kurtas?controller=products&Itemid=

![citruscart_error](https://cloud.githubusercontent.com/assets/1481680/3642874/260aedd6-10c9-11e4-9f06-a726b91d05cf.png)
(tested on Google Chrome Version 36.0.1985.125)

**Comment by priyabose** [comment]
Thank you for reporting your issues, we fixed the issues and now you can download our latest package from our site http://citruscart.com/download.

**Comment by Heart1010** [comment]
Updated my installation. The picture switch when clicking the small icon(s) work now, great! Thanks!

**But** when clicking the big picture it opens the modal window with the original size of that picture. This click on the big picture **brings always the first picture of that product**. 

So I go to the product, click the now showed bigger picture > a modal window with that picture opens. So far so good.
Then I click another picture left (a small one) to change the picture. This works also. Good. 
But when clicking now this bigger picture it opens the modal window with the false picture (the first/default picture is shown)

**Comment by Heart1010** [comment]
This comment 
https://github.com/citruscart/citruscart/commit/3789c7229320dfdeff26094e4f8966e2f3e4dc84#diff-073c9e18ee146ef4d7f66ad4ff38bfa1R87

plus this one 
https://github.com/citruscart/citruscart/commit/ceee52cebe25ea2739a32fef1d43919060981b1f#diff-43fae9dbfa2e11dc7e4ec6bd82437f83R148

fixes the above mentioned problems for me finally
