### ISSUE TITLE
1054 error when search

### ISSUE THREAD

**Issue by transmetent** [citruscart/citruscart#14]
1054 Unknown column 'tbl.privacy' in 'where clause' SQL=SELECT tbl.\* FROM joom3_citruscart_wishlists AS tbl WHERE (LOWER(tbl.wishlist_id) LIKE '%làmpara%' OR LOWER(tbl.wishlist_name) LIKE '%làmpara%') AND tbl.user_id = '18' AND ( ( tbl.privacy = 1 ) OR ( tbl.user_id = '18' ) ) ORDER BY tbl.created_date DESC

**Comment by priyabose** [comment]
we are fixing the issues and soon get back you with the solutions.. Thanks for reporting ..
