### ISSUE TITLE
Product view in admin ("Item is for sale" Yes/No interchanged?)

### ISSUE THREAD

**Issue by Heart1010** [citruscart/citruscart#2]
Admin view > Products > Tab "Pricing And Inventory" > "Item is for sale?" Here Yes / No looks interchanged!?

![bildschirmfoto vom 2014-07-16 22 54 37](https://cloud.githubusercontent.com/assets/1481680/3605454/820d4058-0d2b-11e4-8d46-2917c7f23f09.png)

**Comment by kumarramalingam** [comment]
Hello,
Actually it is not interchange here,
swapping yes and no because  this is a NOT for SALE so the logic is in reverse.
