### ISSUE TITLE
Malware injected

### ISSUE THREAD

**Issue by zamakaziz** [citruscart/citruscart#6]
Hi,

Malware injected through product review page.Kindly help me to avoid that.

Many Thanks.
Abdul Aziz

**Comment by diya5** [comment]
Did you enable ReCaptcha for Reviews in Citruscart config ?

**Comment by zamakaziz** [comment]
No, didn't enable Captcha for citrus cart

**Comment by kumarramalingam** [comment]
Enable ReCaptcha for product review.

Go to,

Citruscart -> Config -> Product settings -> Product reviews.

See 5th option "use CAPTCHA?" label and set "Yes" option.
