### ISSUE TITLE
Citruscart Issues

### ISSUE THREAD

**Issue by ftwg** [citruscart/citruscart#8]
Hi Support, I am building a simple site at www.balmullo-gifts.co.uk. The issue that I am having is showing a category. I can either select table or grid views. The table view shows a list. The grid view only shows "Browse Categories" with no products showing. If you can guide or steer me in the right direction, I would much appreciate that.
Regards
Mike

**Comment by kumarramalingam** [comment]
Hello,

Go to,

Citruscart -> Catalog -> Categories.
You can see all the categories and edit any one category.
set Category Layout File  -> "Select Layout".

**Comment by ftwg** [comment]
Hi Support,
I did that and no difference, so I went to the Config > Default Layouts 
and changed the layouts to "Select Layout" and that worked.

Thanks
Mike

On 07-Aug-14 5:28 AM, kumarramalingam wrote:

> Hello,
> 
> Go to,
> 
> Citruscart -> Catalog -> Categories.
> You can see the all categories and edit any one category.
> set Category Layout File -> "Select Layout".
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/citruscart/citruscart/issues/8#issuecomment-51429965.
> 
> No virus found in this message.
> Checked by AVG - www.avg.com http://www.avg.com
> Version: 2014.0.4744 / Virus Database: 3986/7993 - Release Date: 08/06/14

## 

Best Regards,

Mike Collins,

Google - Affordable Web Design Scotland ... Click on Freetime Webgroup!
Tel - 01334 871101
Mobile - 07851 764 924

This message and any attachments contain privileged and confidential information intended for the use of the addressee named above. If you are not the intended recipient of this message, you are hereby notified that any use, dissemination, distribution or reproduction of this message is prohibited. Please note that we cannot guarantee that this message or any attachment is virus free or that it has not been intercepted and amended. The views of the author may not necessarily reflect those of the Freetime Webgroup.
