### ISSUE TITLE
citrus installation kills joomla page

### ISSUE THREAD

**Issue by worm6666** [citruscart/citruscart#9]
1./ created clean joomla 3 (latest) installation
2./ installed citrus COM
3./ website is killed (blank page without body) - no frontend - no backend...

what to do now ?

**Comment by priyabose** [comment]
Can you provide link to your site ? May help us to fix the issue ..

**Comment by worm6666** [comment]
what kind of access you need ? it was made on my notebook also I should reproduce it somwhere on the LAN where it can run nonstop and give You access like You need...

**Comment by tdguenth** [comment]
I have the same problem. Site hosted on local computer for internal access/testing installed citruscart. Frontend and backend went blank. Can't recover.

**Comment by joomlacorner** [comment]
@worm6666  @tdguenth try this package https://github.com/joomlacorner/citruscart/releases/tag/CitrusCart_v1.2.3-beta1  
and let me know if you still have a problem.

**Comment by worm6666** [comment]
sorry for the delay... also, herewith the results:

Your package, and also latest package from citrus page - no one works. tested on both versions of Joomla 3.3.6 and 2.5.27 (latest stable versions of today)

only one difference between packages (Yours and official) is, that official package turns Joomla unresponsible (no more clicks or "back" browsing possible) - Your package also don't works, but the Joomla still lives. also it can be uninstalled (citrus package) and don't need to create new instance of pure Joomla.

also tested with and without sample data from Joomla - no one works...

**Comment by joomlacorner** [comment]
@worm6666  what's your php version?
Please help to test this package. I have fixed some my mistake.
https://github.com/joomlacorner/citruscart/releases/tag/CitrusCart_v1.2.3-beta2

**Comment by worm6666** [comment]
Yeeeeees. it works NOW ! :-D
1./ on Joomla 3.3.6 - successful install !!!
2./ on Joomla 2.5.27 - with same database - but another table prefix - ERROR (very very much errors)
3./ on Joomla 2.5.27 - new clean database - nothing happens after install (no error only blank page) - after "back" or refresh - backend of Joomla lives - but no extension (component) Citrus is installed - repeating of the install procedure doesn't help... again the same blank page...

and PHP version is: 5.5.9

**Comment by joomlacorner** [comment]
@worm6666  as I know CitrusCart focus to support on Joomla 3.x  not Joomla 2.5.x 
and I found some issue on php higher than 5.3  
I'm working on fixed issue on PHP 5.4 and higher.

**Comment by joomlacorner** [comment]
@diya5  Please merge my pull request to master. it's fixed this issue.

**Comment by joomlacorner** [comment]
Fixed in  https://github.com/citruscart/citruscart/pull/18
